version: "3.8"
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_contact_container
    environment:
      POSTGRES_DB: order_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: order_container
    ports:
      - 8001:8001
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8001 orders.wsgi:application"
    environment:
      DB_HOST: postgres-db
      DB_NAME: order_microservice
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-db

volumes:
  postgres_data:
