version: "3.8"
services:
  postgres-db-orderedproducts:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ordered_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "9207400638" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .  
    volumes:
      - .:/app
    container_name: contactus_container
    ports:
      - 8003:8003
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8003 orderedproducts.wsgi:application"
    environment:
      DB_HOST: postgres-db-orderedproducts
      DB_NAME: ordered_products
      DB_USER: postgres
      DB_PASSWORD: "9207400638"  
    depends_on:
      - postgres-db-orderedproducts

volumes:
  postgres_data:
