# Generated by Django 5.0.3 on 2024-04-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersbackend', '0002_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
