# Generated by Django 5.0.3 on 2024-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersbackend', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='orderaddress',
            old_name='House',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='orderaddress',
            old_name='Street',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productId',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.TextField(default={'id': '2', 'name': 'first'}),
            preserve_default=False,
        ),
    ]
