# Generated by Django 5.0.3 on 2024-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersbackend', '0005_rename_city_orderaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.JSONField(),
        ),
    ]
