export const BaseUrl='http://localhost:8000'
export const OrderUrl='http://localhost:8001'
export const ProductUrl='http://localhost:8002'
export const OrderedProductUrl='http://localhost:8004'
export const ContactUsUrl='http://localhost:8005'